const $=s=>document.querySelector(s), icon=n=>`<svg aria-hidden="true"><use href="#i-${n}"/></svg>`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cases=[
{title:'房屋出售后，承租人要求继续履行租约',tag:'继续履行',date:'示例 A',same:'签约并入住在先，房屋出售在后；租期尚未届满。',diff:'示例中没有提前解约条款争议，实际合同仍需逐项核对。',facts:'承租人与原房东签订两年租约，正常支付租金并入住。租期内房屋出售，新房东要求提前返还房屋。',result:'示例设定：裁判支持继续履行剩余租期。',reason:'这一示例用来呈现“租赁关系建立时间”和“所有权变动时间”的对比，实际裁判需以检索原文为准。'},
{title:'新房东要求腾退，双方争议集中在租约时间',tag:'时间证据',date:'示例 B',same:'发生房屋权属变动，双方对是否可以继续居住有争议。',diff:'租赁文件的签署与实际入住时间存在分歧，需要更完整的证据。',facts:'房屋转让后，承租人提交租约与付款记录主张租赁关系早已成立，受让人对材料形成时间提出异议。',result:'示例设定：裁判重点审查租约、交付及支付凭证。',reason:'仅凭合同落款日期可能不足以还原实际履行情况。本示例强调对比证据，而不是直接套用结论。'},
{title:'合同约定提前解约，承租人主张搬迁损失',tag:'解约约定',date:'示例 C',same:'租期未满即被要求搬离，承租人需要判断后续救济方向。',diff:'双方存在提前解约约定，争议还涉及通知方式和费用承担。',facts:'合同中约定了提前解约安排。房屋转让后，双方就通知期限、押金及搬迁成本发生争议。',result:'示例设定：围绕解约条件及损失证明分别处理。',reason:'同样是提前搬离，合同约定不同，比较重点也不同。本示例用于提醒不能仅看结果是否有利。'},
{title:'欠付租金与腾退要求同时发生',tag:'差异参考',date:'示例 D',same:'新房东要求交还房屋，承租人主张租期尚未结束。',diff:'存在持续欠租事实，与按时付租的情境不同。',facts:'房屋所有权发生变动的同时，承租人存在多期未支付租金的情况。双方对解除及腾退发生争议。',result:'示例设定：同时审查是否存在独立的解除事由。',reason:'不能忽略欠租等关键差异，将此类裁判直接用于支持正常履约的情境。'}];
let state={query:'',region:'',cause:'',purpose:'实务参考',file:'',selected:new Set([0,1,2]),active:0,tab:'overview'},timer;
try{const saved=JSON.parse(sessionStorage.getItem('fxz-research-preview')||'null');if(saved)state={...state,...saved,selected:new Set(saved.selected)}}catch{}
function save(){try{sessionStorage.setItem('fxz-research-preview',JSON.stringify({...state,selected:[...state.selected]}))}catch{}}
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',2600)}
const labels=['描述问题','挑选案例','对比分析','生成报告'];
function steps(n){return `<div class="steps" aria-label="检索流程">${labels.map((s,i)=>`${i?'<i></i>':''}<span class="step ${i<n?'done':i===n?'current':''}" ${i===n?'aria-current="step"':''}><b>${i<n?'✓':i+1}</b>${s}</span>`).join('')}</div>`}
function go(view){save();if(location.hash==='#'+view)render();else location.hash=view}
const example='租赁合同还有8个月到期，我已入住并按时交租。房东把房子卖了，新房东要求两个月内搬走。我想查找类似案例，了解能否继续履行租约。';
function ask(){return `${steps(0)}<section class="intro"><div class="symbol">${icon('search')}</div><h1>找相似的案子，看清不同的结果</h1><p>说说你的情况。我们一起看看，哪些事实真正影响了裁判。</p><form id="ask-form"><div class="composer"><label for="topic">你想查什么？</label><textarea id="topic" required placeholder="例如：房东把房子卖了，新房东让我搬走，但租约还有8个月。我想找找类似案例。">${esc(state.query)}</textarea><div class="composer-bottom"><div class="attachments"><label class="file-label">${icon('file')} 添加参考材料<input id="file" type="file" accept=".pdf,.docx,.txt,.md" aria-label="添加参考材料（仅显示文件名，不读取或上传）"></label><span id="file-name" class="small">${esc(state.file)}</span></div><button class="primary" type="submit">${icon('search')} 体验示例检索</button></div><p class="small" style="margin-top:12px">预览固定演示租房案例；输入内容不会发送，附件仅显示文件名。</p></div><details class="optional"><summary>＋ 补充检索条件 <span class="small">可选</span></summary><div class="fields"><label>地域<input id="region" placeholder="全国" value="${esc(state.region)}"></label><label>案由<input id="cause" placeholder="不确定可以留空" value="${esc(state.cause)}"></label><label>用途<select id="purpose">${['实务参考','课程学习','学术研究'].map(s=>`<option ${s===state.purpose?'selected':''}>${s}</option>`).join('')}</select></label></div></details></form><p class="eyeline">不知道怎么开始？试着从一个问题出发</p><div class="examples">${[['租房纠纷','房东卖房后，新房东让我搬走'],['证据对比','租约时间有争议，需要哪些材料'],['解约争议','提前搬离，搬迁费用如何处理']].map((x,i)=>`<button class="example" data-example="${i}"><strong>${x[0]}</strong><span>${x[1]}</span></button>`).join('')}</div></section>`}
function loading(compare=false){return `${steps(compare?2:0)}<section class="loader" role="status"><div class="scan" aria-hidden="true"><i></i><i></i><i></i><i></i></div><h1>${compare?'把案例放在一起，看看关键差异':'正在整理值得参考的案例'}</h1><p>${compare?'对齐事实、争议与裁判结果，让比较有据可循。':'先找到相似的情境，再辨别真正相关的事实。'}</p><div class="progress-track"><span id="progress"></span></div><div class="stage-list"><span id="s0">${compare?'梳理事实':'检索案例'}</span><span id="s1">${compare?'比较差异':'阅读裁判内容'}</span><span id="s2">${compare?'整理分析':'整理候选案例'}</span></div><p class="small">约 4 秒的模拟演示，未执行真实检索或分析。</p><button data-go="${compare?'pick':'ask'}">返回${compare?'挑选案例':'修改问题'}</button></section>`}
function query(){return `<div class="query"><p><strong>当前问题</strong>　${esc(state.query||example)}</p><button class="quiet" data-go="ask">修改</button></div>`}
function detail(){const c=cases[state.active];return `<article class="paper sticky-detail"><div class="paper-top"><span>${icon('file')} 案例详情</span><span>${c.date} · 虚构案例</span></div><div class="paper-body"><span class="chip">${c.tag}</span><h2>${c.title}</h2><p class="small">无真实法院、案号或裁判文书；仅用于体验信息布局。</p><div class="note-box"><h3 style="margin-top:0">与租房示例的相似点</h3><p>${c.same}</p></div><div class="note-box difference"><h3 style="margin-top:0">需要留意的差异</h3><p>${c.diff}</p></div><h3>案情摘要</h3><p>${c.facts}</p><h3>裁判结果 · 示例</h3><p>${c.result}</p><details class="optional"><summary>查看示例分析说明</summary><p>${c.reason}</p></details><p class="small" style="margin-top:18px">正式接入时，此处提供原文入口及可核对的出处。</p></div></article>`}
function pick(){return `${steps(1)}<div class="page-head"><div><h1>这几篇，值得放在一起看</h1><p>不只看结果是否有利，也看看关键事实是否一致。</p></div><span class="chip">4 篇虚构案例</span></div>${query()}<div class="split"><section><div class="list-top"><span>候选案例 · 点击标题查看详情</span><button class="quiet" id="select-all">${state.selected.size===4?'清空选择':'全选'}</button></div><div class="case-list">${cases.map((c,i)=>`<article class="case-card ${state.active===i?'selected':''}"><input type="checkbox" data-check="${i}" aria-label="选择${c.date}" ${state.selected.has(i)?'checked':''}><div><button class="case-open" data-case="${i}" aria-pressed="${state.active===i}"><div class="case-meta">${c.date} · 虚构案例</div><h3>${c.title}</h3><p>${c.same}</p></button><span class="chip ${i===3?'amber':''}">${c.tag}</span></div></article>`).join('')}</div></section>${detail()}</div><div class="selection-bar"><div>已选 <strong>${state.selected.size}</strong> 篇<small>可自由调整，建议选择 2–3 篇一起对比</small></div><button id="compare" ${state.selected.size<2?'disabled':''}>${state.selected.size<2?'请至少选择 2 篇':'对比所选案例 '+icon('arrow')}</button></div>`}
function reportBody(){return `<span class="chip">设计预览 · 非真实研究报告</span><h1>房屋出售后的租约履行问题</h1><p class="sub">类案检索与对比报告 · 已选 ${state.selected.size} 篇虚构案例</p><h2>一、检索问题</h2><p>${esc(state.query||example)}</p><h2>二、阅读提示</h2><p>本报告仅展示版式与操作流程。下列案例与分析全部为虚构示例，没有检索真实裁判文书，也未核验法律依据，不能作为法律判断依据。</p><h2>三、案例对比摘要</h2>${[...state.selected].sort().map(i=>`<h3 style="margin:20px 0 8px">${cases[i].date}：${cases[i].title}</h3><p>相似点：${cases[i].same}</p><p>关键差异：${cases[i].diff}</p>`).join('')}<h2>四、后续核对清单</h2><p>核对租约签订、交付入住、所有权变动的时间；补充付款与沟通记录；检查合同中的提前解约约定。此处为示例工作清单。</p><h2>五、资料来源</h2><ul class="report-cases">${[...state.selected].sort().map(i=>`<li>${cases[i].date} · ${cases[i].title}（虚构，无原文链接）</li>`).join('')}</ul>`}
function analysis(){const ids=[...state.selected].sort();return `${steps(2)}<div class="page-head"><div><h1>相似的争议，差异在这里</h1><p>已将你选择的 ${ids.length} 篇案例放在一起对比。</p></div><button data-go="pick">调整案例</button></div><div class="tabs" role="tablist" aria-label="分析内容">${[['overview','主要发现'],['matrix','逐案对比'],['evidence','待核对材料']].map(([id,l])=>`<button role="tab" aria-selected="${state.tab===id}" class="${state.tab===id?'active':''}" data-tab="${id}">${l}</button>`).join('')}</div><section role="tabpanel">${state.tab==='overview'?`<div class="finding"><span class="chip">示例分析 · 未核验</span><h2>先对齐关键事实，再判断案例能否参考</h2><p>“房屋出售后要求搬离”只是共同情境。租赁建立时间、合同约定及履约情况，才是这组示例中需要进一步比较的内容。</p></div><div class="analysis-grid"><section><h3>所选案例给出的比较方向</h3>${ids.map(i=>`<p style="margin:18px 0">${cases[i].same}<button class="source-button" data-source="${i}">${cases[i].date} 查看</button></p>`).join('')}</section><section><h3>不要忽略这些区别</h3><ul>${ids.map(i=>`<li>${cases[i].diff}</li>`).join('')}</ul></section></div>`:state.tab==='matrix'?`<div class="table-scroll"><table><thead><tr><th>对比维度</th>${ids.map(i=>`<th>${cases[i].date} · ${cases[i].tag}</th>`).join('')}</tr></thead><tbody>${[['关键事实','facts'],['相似之处','same'],['重要差异','diff'],['示例结果','result']].map(([l,k])=>`<tr><th>${l}</th>${ids.map(i=>`<td>${cases[i][k]}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:`<article class="paper paper-body"><h2>把这些材料补齐，比较才更有意义</h2><p>以下仅为演示清单，勾选表示你已查看，不代表完成法律核验。</p>${['租赁合同及补充协议：核对时间与提前解约条款','租金付款记录、交付记录：了解实际履行情况','搬离通知及沟通记录：核对提出要求的理由','权属变动相关材料：厘清时间顺序'].map(x=>`<label style="display:flex;gap:14px;padding:16px 0;border-bottom:1px solid var(--line)"><input type="checkbox">${x}</label>`).join('')}</article>`}</section><div class="action-row"><button data-go="pick">返回挑选案例</button><button class="primary" data-go="report">预览研究报告 ${icon('arrow')}</button></div>`}
function report(){return `${steps(3)}<div class="page-head"><div><h1>把研究过程，整理成一份报告</h1><p>案例、差异与待核对事项，放在一起方便复查。</p></div><button data-go="analysis">返回分析</button></div><div class="report-layout"><article class="paper report-paper" id="report-content">${reportBody()}</article><aside class="export-box"><h3>报告已准备好</h3><p>包含问题描述、所选案例对比及材料清单。</p><span class="chip">${state.selected.size} 篇示例案例</span><button id="download" class="primary">${icon('download')} 下载示例报告</button><button id="print">打印 / 保存 PDF</button><p>下载格式为 HTML。所有页面均保留“虚构示例”标识。</p><hr style="border:0;border-top:1px solid var(--line);margin:22px 0"><p>正式接入时提供 Word 导出，并保留真实案例出处和依据核验状态。</p><button data-go="ask">修改检索问题</button></aside></div>`}
function bind(){document.querySelectorAll('[data-go]').forEach(el=>el.onclick=()=>go(el.dataset.go));document.querySelectorAll('[data-example]').forEach(el=>el.onclick=()=>{state.query=[example,'租约签署时间有争议，我想比较法院如何审查入住和付款证据。','租期未满房东要求搬离，我想比较提前解约约定与搬迁损失的处理。'][+el.dataset.example];$('#topic').value=state.query;save();$('#topic').focus()});const form=$('#ask-form');if(form){$('#topic').oninput=e=>{state.query=e.target.value;save()};['region','cause','purpose'].forEach(id=>$('#'+id).onchange=e=>{state[id]=e.target.value;save()});$('#file').onchange=e=>{state.file=e.target.files[0]?.name||'';$('#file-name').textContent=state.file;save()};form.onsubmit=e=>{e.preventDefault();if(!state.query.trim())return;go('searching')}}document.querySelectorAll('[data-case]').forEach(el=>el.onclick=()=>{state.active=+el.dataset.case;save();render(false);document.querySelector(`[data-case="${state.active}"]`).focus({preventScroll:true});if(matchMedia("(max-width:760px)").matches)$(".sticky-detail").scrollIntoView({behavior:matchMedia("(prefers-reduced-motion:reduce)").matches?"instant":"smooth",block:"start"})});document.querySelectorAll('[data-check]').forEach(el=>el.onchange=()=>{const i=+el.dataset.check;el.checked?state.selected.add(i):state.selected.delete(i);save();render(false);document.querySelector(`[data-check="${i}"]`).focus({preventScroll:true})});if($('#select-all'))$('#select-all').onclick=()=>{state.selected=state.selected.size===4?new Set():new Set([0,1,2,3]);save();render(false)};if($('#compare'))$('#compare').onclick=()=>go('comparing');document.querySelectorAll('[data-tab]').forEach(el=>el.onclick=()=>{state.tab=el.dataset.tab;save();render(false);document.querySelector(`[data-tab="${state.tab}"]`).focus()});document.querySelectorAll('[data-source]').forEach(el=>el.onclick=()=>{state.active=+el.dataset.source;go('pick')});if($('#download'))$('#download').onclick=()=>{const text='<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>类案研究报告（虚构示例）</title><body style="max-width:800px;margin:40px auto;font:16px/1.9 sans-serif;padding:24px">'+reportBody()+'</body></html>';const url=URL.createObjectURL(new Blob([text],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='法小智-类案研究报告-虚构示例.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('示例报告已下载')};if($('#print'))$('#print').onclick=()=>window.print()}
function render(scroll=true){clearInterval(timer);let view=location.hash.slice(1)||'ask';if(!['ask','searching','pick','comparing','analysis','report'].includes(view))view='ask';if(['analysis','comparing','report'].includes(view)&&state.selected.size<2){go('pick');return}$('#main').innerHTML=`<div class="view">${({ask,pick,analysis,report,searching:()=>loading(),comparing:()=>loading(true)})[view]()}</div>`;bind();if(scroll){window.scrollTo(0,0);$('#main').focus({preventScroll:true})}if(view==='searching'||view==='comparing'){let t=0;timer=setInterval(()=>{t++;const p=$('#progress');if(p)p.style.width=(t/4*100)+'%';for(let i=0;i<3;i++)if($('#s'+i)&&t>i)$('#s'+i).classList.add('done');if(t===4){clearInterval(timer);go(view==='searching'?'pick':'analysis')}},1000)}}
$('#collapse').onclick=()=>{const compact=document.body.classList.toggle('compact');$('#collapse').setAttribute('aria-expanded',String(!compact));$('#collapse').setAttribute('aria-label',compact?'展开导航':'收起导航')};window.addEventListener('hashchange',()=>render());render();
