"use client";
import { useRef } from "react";
import { Upload, FileSearch, FileText, Download, ShieldCheck } from "lucide-react";
import type { MaterialItem } from "@/lib/api/types";
import { STANCE_FALLBACK_LABELS } from "@/lib/api/contract";
import { SAMPLE_CONTRACT_NAME, SAMPLE_CONTRACT_TEXT } from "./sample-contract";

export function ContractIntake({material,uploading,stance,onStance,onUpload,onVerify,onReset,onStart,canStart,requirements,onRequirements}: {
 material?:MaterialItem; uploading:boolean; stance:string; onStance:(v:string)=>void; onUpload:(files:File[])=>void; onVerify:(id:string)=>void; onReset:()=>void; onStart:()=>void; canStart:boolean; requirements:string; onRequirements:(v:string)=>void;
}) {
 const input=useRef<HTMLInputElement>(null);
 return !material ? <div className="cx-intake"><section className="ct-card"><div className="cx-drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!uploading)onUpload(Array.from(e.dataTransfer.files));}}><div className="cx-file-icon"><Upload size={28}/></div><h2>拖入合同，或选择文件</h2><p className="ct-lead">支持 DOCX、PDF、TXT、MD · 一次一份</p><input ref={input} type="file" hidden accept=".docx,.pdf,.txt,.md" onChange={e=>{onUpload(Array.from(e.target.files??[]));e.target.value="";}}/><button className="ct-btn ct-btn-primary" disabled={uploading} onClick={()=>input.current?.click()}><Upload size={17}/>{uploading?"正在上传并读取…":"选择合同"}</button></div><p className="cx-privacy"><ShieldCheck size={16}/>请上传可复制文字的合同，扫描件暂不支持。</p><div className="cx-sample"><div><strong>先看看审查是什么样的</strong><p className="ct-mini">示例合同也会调用真实审查服务</p></div><button className="ct-btn" disabled={uploading} onClick={()=>onUpload([new File([SAMPLE_CONTRACT_TEXT],SAMPLE_CONTRACT_NAME,{type:"text/plain"})])}>用示例体验</button></div></section><aside className="cx-benefits"><h2>不止找出问题，<br/>也帮你把修改落到纸上。</h2>{[[FileSearch,"对照原文，看清影响","点一条风险，就能查看它对应的合同原话。"],[FileText,"逐条斟酌，留下改法","编辑修改建议，记录采纳与待确认事项。"],[Download,"整理成报告，方便沟通","汇总风险、依据与修改意见，导出 Word 报告。"]] .map(([Icon,title,desc])=>{const I=Icon as typeof FileSearch;return <div key={String(title)}><I size={21}/><section><h3>{String(title)}</h3><p>{String(desc)}</p></section></div>;})}</aside></div> : <><div className="ct-file"><FileText/><div><strong>{String(material.filename??"已上传合同")}</strong><span>{material.verified?"已核验":"已接收 · 请确认本次审查对象"}</span></div><button className="ct-btn" onClick={onReset}>更换合同</button></div><div className="cx-setup"><section className="ct-card"><h2>你代表哪一方？</h2><p className="ct-lead">以合同中实际标注的甲乙方为准。</p><div className="ct-stance" role="radiogroup" aria-label="我是哪一方">{Object.entries(STANCE_FALLBACK_LABELS).map(([value,label])=><label key={value} className="ct-stance-item" data-active={stance===value}><input type="radio" name="stance" checked={stance===value} onChange={()=>onStance(value)}/><strong>{label}</strong></label>)}</div><label className="ct-check"><input type="checkbox" checked={Boolean(material.verified)} disabled={Boolean(material.verified)} onChange={()=>onVerify(String(material.source_id))}/><span>本人已核验这份合同<em>确认上传的是本次要审查的版本。</em></span></label></section><section className="ct-card"><label htmlFor="contract-requirements"><h2>有没有特别想关注的？</h2></label><p className="ct-lead">可选。补充背景，让审查更贴合这次合作。</p><textarea id="contract-requirements" className="ct-input" rows={6} maxLength={2000} value={requirements} onChange={e=>onRequirements(e.target.value)} placeholder="例如：还没签约，想重点检查付款、验收和违约责任。"/><p className="ct-mini">补充内容会随合同一起交给审查模型。</p></section></div><div className="cx-bottom"><p className="ct-mini">{!material.verified?"请核验合同后继续。":!stance?"请选择审查立场。":"准备好后开始审查，将使用当前配置的模型及检索服务。"}</p><button className="ct-btn ct-btn-primary" disabled={!canStart} onClick={onStart}><FileSearch size={17}/>开始审查</button></div></>;
}
